name: portfolio
description: Bakhromjon Polat's portfolio

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  sendgrid_mailer: ^0.1.3
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:      
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500        
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600

